version: '3.5'

services:
  python_orgmode:
    container_name: python_orgmode
    build: .
    volumes:
      - '.:/app'
      - 'local:/root/.local'
    tty: true
    stdin_open: true
volumes:
  local:
